# Generated by Django 3.2.6 on 2021-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustworkApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='user_name',
        ),
        migrations.AddField(
            model_name='test2',
            name='email',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test2',
            name='firstname',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test2',
            name='lastname',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test2',
            name='standard',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
